package com.govt.centralgovt;

import com.govt.centralgovt.schmes.*;

public class CentralGovtRunner {

    public static void main(String[] args) {

        System.out.println("Karntaka schemes under central government");
        CentralGovt centralGovt=new Karnataka();
        centralGovt.janDhanYojana();
        centralGovt.awasYojana();
        centralGovt.ujjwalaYojana();
        centralGovt.kisanSammanNidhi();
        centralGovt.mudraYojana();
        centralGovt.ayushmanBharat();
        centralGovt.swachhBharatMission();
        centralGovt.betiBachaoBetiPadhao();
        centralGovt.skillIndia();
        centralGovt.digitalIndia();
        centralGovt.makeInIndia();
        centralGovt.startupIndia();
        centralGovt.fasalBimaYojana();
        centralGovt.atalPensionYojana();
        centralGovt.jeevanJyotiBimaYojana();
        centralGovt.surakshaBimaYojana();
        centralGovt.nationalEducationPolicy();
        centralGovt.pmGatiShakti();
        centralGovt.standUpIndia();
        centralGovt.svanidhiYojana();

        System.out.println("---------------------------------------------");
        System.out.println("Tamil nadu schemes under central government");
        CentralGovt centralGovt1=new TamilNadu();
        centralGovt1.janDhanYojana();
        centralGovt1.awasYojana();
        centralGovt1.ujjwalaYojana();
        centralGovt1.kisanSammanNidhi();
        centralGovt1.mudraYojana();
        centralGovt1.ayushmanBharat();
        centralGovt1.swachhBharatMission();
        centralGovt1.betiBachaoBetiPadhao();
        centralGovt1.skillIndia();
        centralGovt1.digitalIndia();
        centralGovt1.makeInIndia();
        centralGovt1.startupIndia();
        centralGovt1.fasalBimaYojana();
        centralGovt1.atalPensionYojana();
        centralGovt1.jeevanJyotiBimaYojana();
        centralGovt1.surakshaBimaYojana();
        centralGovt1.nationalEducationPolicy();
        centralGovt1.pmGatiShakti();
        centralGovt1.standUpIndia();
        centralGovt1.svanidhiYojana();

        System.out.println("---------------------------------------------");
        System.out.println("Kerala schemes under central government");
        CentralGovt centralGovt2=new Kerala();
        centralGovt2.janDhanYojana();
        centralGovt2.awasYojana();
        centralGovt2.ujjwalaYojana();
        centralGovt2.kisanSammanNidhi();
        centralGovt2.mudraYojana();
        centralGovt2.ayushmanBharat();
        centralGovt2.swachhBharatMission();
        centralGovt2.betiBachaoBetiPadhao();
        centralGovt2.skillIndia();
        centralGovt2.digitalIndia();
        centralGovt2.makeInIndia();
        centralGovt2.startupIndia();
        centralGovt2.fasalBimaYojana();
        centralGovt2.atalPensionYojana();
        centralGovt2.jeevanJyotiBimaYojana();
        centralGovt2.surakshaBimaYojana();
        centralGovt2.nationalEducationPolicy();
        centralGovt2.pmGatiShakti();
        centralGovt2.standUpIndia();
        centralGovt2.svanidhiYojana();

        System.out.println("---------------------------------------------");
        System.out.println("Andhrapradesh schemes under central government");
        CentralGovt centralGovt3=new AndhraPradesh();
        centralGovt3.janDhanYojana();
        centralGovt3.awasYojana();
        centralGovt3.ujjwalaYojana();
        centralGovt3.kisanSammanNidhi();
        centralGovt3.mudraYojana();
        centralGovt3.ayushmanBharat();
        centralGovt3.swachhBharatMission();
        centralGovt3.betiBachaoBetiPadhao();
        centralGovt3.skillIndia();
        centralGovt3.digitalIndia();
        centralGovt3.makeInIndia();
        centralGovt3.startupIndia();
        centralGovt3.fasalBimaYojana();
        centralGovt3.atalPensionYojana();
        centralGovt3.jeevanJyotiBimaYojana();
        centralGovt3.surakshaBimaYojana();
        centralGovt3.nationalEducationPolicy();
        centralGovt3.pmGatiShakti();
        centralGovt3.standUpIndia();
        centralGovt3.svanidhiYojana();

        System.out.println("---------------------------------------------");
        System.out.println("Telangana schemes under central government");
        CentralGovt centralGovt4=new Telangana();
        centralGovt4.janDhanYojana();
        centralGovt4.awasYojana();
        centralGovt4.ujjwalaYojana();
        centralGovt4.kisanSammanNidhi();
        centralGovt4.mudraYojana();
        centralGovt4.ayushmanBharat();
        centralGovt4.swachhBharatMission();
        centralGovt4.betiBachaoBetiPadhao();
        centralGovt4.skillIndia();
        centralGovt4.digitalIndia();
        centralGovt4.makeInIndia();
        centralGovt4.startupIndia();
        centralGovt4.fasalBimaYojana();
        centralGovt4.atalPensionYojana();
        centralGovt4.jeevanJyotiBimaYojana();
        centralGovt4.surakshaBimaYojana();
        centralGovt4.nationalEducationPolicy();
        centralGovt4.pmGatiShakti();
        centralGovt4.standUpIndia();
        centralGovt4.svanidhiYojana();

        System.out.println("---------------------------------------------");
        System.out.println("Maharashtra schemes under central government");
        CentralGovt centralGovt5=new Maharashtra();
        centralGovt5.janDhanYojana();
        centralGovt5.awasYojana();
        centralGovt5.ujjwalaYojana();
        centralGovt5.kisanSammanNidhi();
        centralGovt5.mudraYojana();
        centralGovt5.ayushmanBharat();
        centralGovt5.swachhBharatMission();
        centralGovt5.betiBachaoBetiPadhao();
        centralGovt5.skillIndia();
        centralGovt5.digitalIndia();
        centralGovt5.makeInIndia();
        centralGovt5.startupIndia();
        centralGovt5.fasalBimaYojana();
        centralGovt5.atalPensionYojana();
        centralGovt5.jeevanJyotiBimaYojana();
        centralGovt5.surakshaBimaYojana();
        centralGovt5.nationalEducationPolicy();
        centralGovt5.pmGatiShakti();
        centralGovt5.standUpIndia();
        centralGovt5.svanidhiYojana();


        System.out.println("---------------------------------------------");
        System.out.println("Gujarat schemes under central government");
        CentralGovt centralGovt6=new Gujarat();
        centralGovt6.janDhanYojana();
        centralGovt6.awasYojana();
        centralGovt6.ujjwalaYojana();
        centralGovt6.kisanSammanNidhi();
        centralGovt6.mudraYojana();
        centralGovt6.ayushmanBharat();
        centralGovt6.swachhBharatMission();
        centralGovt6.betiBachaoBetiPadhao();
        centralGovt6.skillIndia();
        centralGovt6.digitalIndia();
        centralGovt6.makeInIndia();
        centralGovt6.startupIndia();
        centralGovt6.fasalBimaYojana();
        centralGovt6.atalPensionYojana();
        centralGovt6.jeevanJyotiBimaYojana();
        centralGovt6.surakshaBimaYojana();
        centralGovt6.nationalEducationPolicy();
        centralGovt6.pmGatiShakti();
        centralGovt6.standUpIndia();
        centralGovt6.svanidhiYojana();

        System.out.println("---------------------------------------------");
        System.out.println("Rajasthan schemes under central government");
        CentralGovt centralGovt7=new Rajasthan();
        centralGovt7.janDhanYojana();
        centralGovt7.awasYojana();
        centralGovt7.ujjwalaYojana();
        centralGovt7.kisanSammanNidhi();
        centralGovt7.mudraYojana();
        centralGovt7.ayushmanBharat();
        centralGovt7.swachhBharatMission();
        centralGovt7.betiBachaoBetiPadhao();
        centralGovt7.skillIndia();
        centralGovt7.digitalIndia();
        centralGovt7.makeInIndia();
        centralGovt7.startupIndia();
        centralGovt7.fasalBimaYojana();
        centralGovt7.atalPensionYojana();
        centralGovt7.jeevanJyotiBimaYojana();
        centralGovt7.surakshaBimaYojana();
        centralGovt7.nationalEducationPolicy();
        centralGovt7.pmGatiShakti();
        centralGovt7.standUpIndia();
        centralGovt7.svanidhiYojana();


        System.out.println("---------------------------------------------");
        System.out.println("Punjab schemes under central government");
        CentralGovt centralGovt8=new Punjab();
        centralGovt8.janDhanYojana();
        centralGovt8.awasYojana();
        centralGovt8.ujjwalaYojana();
        centralGovt8.kisanSammanNidhi();
        centralGovt8.mudraYojana();
        centralGovt8.ayushmanBharat();
        centralGovt8.swachhBharatMission();
        centralGovt8.betiBachaoBetiPadhao();
        centralGovt8.skillIndia();
        centralGovt8.digitalIndia();
        centralGovt8.makeInIndia();
        centralGovt8.startupIndia();
        centralGovt8.fasalBimaYojana();
        centralGovt8.atalPensionYojana();
        centralGovt8.jeevanJyotiBimaYojana();
        centralGovt8.surakshaBimaYojana();
        centralGovt8.nationalEducationPolicy();
        centralGovt8.pmGatiShakti();
        centralGovt8.standUpIndia();
        centralGovt8.svanidhiYojana();

        System.out.println("---------------------------------------------");
        System.out.println("Haryana schemes under central government");
        CentralGovt centralGovt9=new Haryana();
        centralGovt9.janDhanYojana();
        centralGovt9.awasYojana();
        centralGovt9.ujjwalaYojana();
        centralGovt9.kisanSammanNidhi();
        centralGovt9.mudraYojana();
        centralGovt9.ayushmanBharat();
        centralGovt9.swachhBharatMission();
        centralGovt9.betiBachaoBetiPadhao();
        centralGovt9.skillIndia();
        centralGovt9.digitalIndia();
        centralGovt9.makeInIndia();
        centralGovt9.startupIndia();
        centralGovt9.fasalBimaYojana();
        centralGovt9.atalPensionYojana();
        centralGovt9.jeevanJyotiBimaYojana();
        centralGovt9.surakshaBimaYojana();
        centralGovt9.nationalEducationPolicy();
        centralGovt9.pmGatiShakti();
        centralGovt9.standUpIndia();
        centralGovt9.svanidhiYojana();

        System.out.println("---------------------------------------------");
        System.out.println("UttarPradesh schemes under central government");
        CentralGovt centralGovt10=new UttarPradesh();
        centralGovt10.janDhanYojana();
        centralGovt10.awasYojana();
        centralGovt10.ujjwalaYojana();
        centralGovt10.kisanSammanNidhi();
        centralGovt10.mudraYojana();
        centralGovt10.ayushmanBharat();
        centralGovt10.swachhBharatMission();
        centralGovt10.betiBachaoBetiPadhao();
        centralGovt10.skillIndia();
        centralGovt10.digitalIndia();
        centralGovt10.makeInIndia();
        centralGovt10.startupIndia();
        centralGovt10.fasalBimaYojana();
        centralGovt10.atalPensionYojana();
        centralGovt10.jeevanJyotiBimaYojana();
        centralGovt10.surakshaBimaYojana();
        centralGovt10.nationalEducationPolicy();
        centralGovt10.pmGatiShakti();
        centralGovt10.standUpIndia();
        centralGovt10.svanidhiYojana();

        System.out.println("---------------------------------------------");
        System.out.println("WestBengal schemes under central government");
        CentralGovt centralGovt11=new WestBengal();
        centralGovt11.janDhanYojana();
        centralGovt11.awasYojana();
        centralGovt11.ujjwalaYojana();
        centralGovt11.kisanSammanNidhi();
        centralGovt11.mudraYojana();
        centralGovt11.ayushmanBharat();
        centralGovt11.swachhBharatMission();
        centralGovt11.betiBachaoBetiPadhao();
        centralGovt11.skillIndia();
        centralGovt11.digitalIndia();
        centralGovt11.makeInIndia();
        centralGovt11.startupIndia();
        centralGovt11.fasalBimaYojana();
        centralGovt11.atalPensionYojana();
        centralGovt11.jeevanJyotiBimaYojana();
        centralGovt11.surakshaBimaYojana();
        centralGovt11.nationalEducationPolicy();
        centralGovt11.pmGatiShakti();
        centralGovt11.standUpIndia();
        centralGovt11.svanidhiYojana();

        System.out.println("---------------------------------------------");
        System.out.println("Odisha schemes under central government");
        CentralGovt centralGovt12=new Odisha();
        centralGovt12.janDhanYojana();
        centralGovt12.awasYojana();
        centralGovt12.ujjwalaYojana();
        centralGovt12.kisanSammanNidhi();
        centralGovt12.mudraYojana();
        centralGovt12.ayushmanBharat();
        centralGovt12.swachhBharatMission();
        centralGovt12.betiBachaoBetiPadhao();
        centralGovt12.skillIndia();
        centralGovt12.digitalIndia();
        centralGovt12.makeInIndia();
        centralGovt12.startupIndia();
        centralGovt12.fasalBimaYojana();
        centralGovt12.atalPensionYojana();
        centralGovt12.jeevanJyotiBimaYojana();
        centralGovt12.surakshaBimaYojana();
        centralGovt12.nationalEducationPolicy();
        centralGovt12.pmGatiShakti();
        centralGovt12.standUpIndia();
        centralGovt12.svanidhiYojana();

        System.out.println("---------------------------------------------");
        System.out.println("Bihar schemes under central government");
        CentralGovt centralGovt13=new Bihar();
        centralGovt13.janDhanYojana();
        centralGovt13.awasYojana();
        centralGovt13.ujjwalaYojana();
        centralGovt13.kisanSammanNidhi();
        centralGovt13.mudraYojana();
        centralGovt13.ayushmanBharat();
        centralGovt13.swachhBharatMission();
        centralGovt13.betiBachaoBetiPadhao();
        centralGovt13.skillIndia();
        centralGovt13.digitalIndia();
        centralGovt13.makeInIndia();
        centralGovt13.startupIndia();
        centralGovt13.fasalBimaYojana();
        centralGovt13.atalPensionYojana();
        centralGovt13.jeevanJyotiBimaYojana();
        centralGovt13.surakshaBimaYojana();
        centralGovt13.nationalEducationPolicy();
        centralGovt13.pmGatiShakti();
        centralGovt13.standUpIndia();
        centralGovt13.svanidhiYojana();





    }
}
