package com.rbi.banks;

import com.rbi.banks.bank.*;

public class BankRunner {

    public static void main(String[] args) {

        Rbi rbi =new SbiBank();
        System.out.println("SBI bank schmes");
        rbi.kyc();
        rbi.openAccount();
        rbi.closeAccount();
        rbi.depositMoney();
        rbi.withdrawMoney();
        rbi.transferMoney();
        rbi.checkBalance();
        rbi.updateAccountDetails();
        rbi.verifyCustomer();
        rbi.issueDebitCard();
        rbi.blockDebitCard();
        rbi.activateDebitCard();
        rbi.issueCreditCard();
        rbi.blockCreditCard();
        rbi.approveLoan();
        rbi.rejectLoan();
        rbi.calculateInterest();
        rbi.updateInterestRate();
        rbi.checkKycStatus();
        rbi.updateKycDetails();
        rbi.generateBankStatement();
        rbi.processCheque();
        rbi.stopChequePayment();
        rbi.updateNominee();
        rbi.freezeAccount();
        rbi.unfreezeAccount();


        System.out.println("------------------------------------------------");
        System.out.println("HDFC bank schmes");
        Rbi rbi1=new Hdfc();
        rbi1.kyc();
        rbi1.openAccount();
        rbi1.closeAccount();
        rbi1.depositMoney();
        rbi1.withdrawMoney();
        rbi1.transferMoney();
        rbi1.checkBalance();
        rbi1.updateAccountDetails();
        rbi1.verifyCustomer();
        rbi1.issueDebitCard();
        rbi1.blockDebitCard();
        rbi1.activateDebitCard();
        rbi1.issueCreditCard();
        rbi1.blockCreditCard();
        rbi1.approveLoan();
        rbi1.rejectLoan();
        rbi1.calculateInterest();
        rbi1.updateInterestRate();
        rbi1.checkKycStatus();
        rbi1.updateKycDetails();
        rbi1.generateBankStatement();
        rbi1.processCheque();
        rbi1.stopChequePayment();
        rbi1.updateNominee();
        rbi1.freezeAccount();
        rbi1.unfreezeAccount();

        System.out.println("-------------------------------------------------------");
        System.out.println("ICICI bank schmes");
        Rbi rbi2=new Icici();
        rbi2.kyc();
        rbi2.openAccount();
        rbi2.closeAccount();
        rbi2.depositMoney();
        rbi2.withdrawMoney();
        rbi2.transferMoney();
        rbi2.checkBalance();
        rbi2.updateAccountDetails();
        rbi2.verifyCustomer();
        rbi2.issueDebitCard();
        rbi2.blockDebitCard();
        rbi2.activateDebitCard();
        rbi2.issueCreditCard();
        rbi2.blockCreditCard();
        rbi2.approveLoan();
        rbi2.rejectLoan();
        rbi2.calculateInterest();
        rbi2.updateInterestRate();
        rbi2.checkKycStatus();
        rbi2.updateKycDetails();
        rbi2.generateBankStatement();
        rbi2.processCheque();
        rbi2.stopChequePayment();
        rbi2.updateNominee();
        rbi2.freezeAccount();
        rbi2.unfreezeAccount();


        System.out.println("-------------------------------------------------------");
        System.out.println("Axis bank schmes");
        Rbi rbi3=new Axis();
        rbi3.kyc();
        rbi3.openAccount();
        rbi3.closeAccount();
        rbi3.depositMoney();
        rbi3.withdrawMoney();
        rbi3.transferMoney();
        rbi3.checkBalance();
        rbi3.updateAccountDetails();
        rbi3.verifyCustomer();
        rbi3.issueDebitCard();
        rbi3.blockDebitCard();
        rbi3.activateDebitCard();
        rbi3.issueCreditCard();
        rbi3.blockCreditCard();
        rbi3.approveLoan();
        rbi3.rejectLoan();
        rbi3.calculateInterest();
        rbi3.updateInterestRate();
        rbi3.checkKycStatus();
        rbi3.updateKycDetails();
        rbi3.generateBankStatement();
        rbi3.processCheque();
        rbi3.stopChequePayment();
        rbi3.updateNominee();
        rbi3.freezeAccount();
        rbi3.unfreezeAccount();


        System.out.println("-------------------------------------------------------");
        System.out.println("Kotak Mahindra bank schmes");
        Rbi rbi4=new KotakMahindra();
        rbi4.kyc();
        rbi4.openAccount();
        rbi4.closeAccount();
        rbi4.depositMoney();
        rbi4.withdrawMoney();
        rbi4.transferMoney();
        rbi4.checkBalance();
        rbi4.updateAccountDetails();
        rbi4.verifyCustomer();
        rbi4.issueDebitCard();
        rbi4.blockDebitCard();
        rbi4.activateDebitCard();
        rbi4.issueCreditCard();
        rbi4.blockCreditCard();
        rbi4.approveLoan();
        rbi4.rejectLoan();
        rbi4.calculateInterest();
        rbi4.updateInterestRate();
        rbi4.checkKycStatus();
        rbi4.updateKycDetails();
        rbi4.generateBankStatement();
        rbi4.processCheque();
        rbi4.stopChequePayment();
        rbi4.updateNominee();
        rbi4.freezeAccount();
        rbi4.unfreezeAccount();


        System.out.println("-------------------------------------------------------");
        System.out.println("IndusInd Bank  schemes");
        Rbi rbi5=new IndusInd();
        rbi5.kyc();
        rbi5.openAccount();
        rbi5.closeAccount();
        rbi5.depositMoney();
        rbi5.withdrawMoney();
        rbi5.transferMoney();
        rbi5.checkBalance();
        rbi5.updateAccountDetails();
        rbi5.verifyCustomer();
        rbi5.issueDebitCard();
        rbi5.blockDebitCard();
        rbi5.activateDebitCard();
        rbi5.issueCreditCard();
        rbi5.blockCreditCard();
        rbi5.approveLoan();
        rbi5.rejectLoan();
        rbi5.calculateInterest();
        rbi5.updateInterestRate();
        rbi5.checkKycStatus();
        rbi5.updateKycDetails();
        rbi5.generateBankStatement();
        rbi5.processCheque();
        rbi5.stopChequePayment();
        rbi5.updateNominee();
        rbi5.freezeAccount();
        rbi5.unfreezeAccount();


        System.out.println("-------------------------------------------------------");
        System.out.println("Bank of baroda schmes");
        Rbi rbi6=new BankofBaroda();
        rbi6.kyc();
        rbi6.openAccount();
        rbi6.closeAccount();
        rbi6.depositMoney();
        rbi6.withdrawMoney();
        rbi6.transferMoney();
        rbi6.checkBalance();
        rbi6.updateAccountDetails();
        rbi6.verifyCustomer();
        rbi6.issueDebitCard();
        rbi6.blockDebitCard();
        rbi6.activateDebitCard();
        rbi6.issueCreditCard();
        rbi6.blockCreditCard();
        rbi6.approveLoan();
        rbi6.rejectLoan();
        rbi6.calculateInterest();
        rbi6.updateInterestRate();
        rbi6.checkKycStatus();
        rbi6.updateKycDetails();
        rbi6.generateBankStatement();
        rbi6.processCheque();
        rbi6.stopChequePayment();
        rbi6.updateNominee();
        rbi6.freezeAccount();
        rbi6.unfreezeAccount();


        System.out.println("-------------------------------------------------------");
        System.out.println("Punjab National Bank schmes");
        Rbi rbi7=new PunjabNationalBank();
        rbi7.kyc();
        rbi7.openAccount();
        rbi7.closeAccount();
        rbi7.depositMoney();
        rbi7.withdrawMoney();
        rbi7.transferMoney();
        rbi7.checkBalance();
        rbi7.updateAccountDetails();
        rbi7.verifyCustomer();
        rbi7.issueDebitCard();
        rbi7.blockDebitCard();
        rbi7.activateDebitCard();
        rbi7.issueCreditCard();
        rbi7.blockCreditCard();
        rbi7.approveLoan();
        rbi7.rejectLoan();
        rbi7.calculateInterest();
        rbi7.updateInterestRate();
        rbi7.checkKycStatus();
        rbi7.updateKycDetails();
        rbi7.generateBankStatement();
        rbi7.processCheque();
        rbi7.stopChequePayment();
        rbi7.updateNominee();
        rbi7.freezeAccount();
        rbi7.unfreezeAccount();


        System.out.println("-------------------------------------------------------");
        System.out.println("Canara Bank schmes");
        Rbi rbi8=new Canara();
        rbi8.kyc();
        rbi8.openAccount();
        rbi8.closeAccount();
        rbi8.depositMoney();
        rbi8.withdrawMoney();
        rbi8.transferMoney();
        rbi8.checkBalance();
        rbi8.updateAccountDetails();
        rbi8.verifyCustomer();
        rbi8.issueDebitCard();
        rbi8.blockDebitCard();
        rbi8.activateDebitCard();
        rbi8.issueCreditCard();
        rbi8.blockCreditCard();
        rbi8.approveLoan();
        rbi8.rejectLoan();
        rbi8.calculateInterest();
        rbi8.updateInterestRate();
        rbi8.checkKycStatus();
        rbi8.updateKycDetails();
        rbi8.generateBankStatement();
        rbi8.processCheque();
        rbi8.stopChequePayment();
        rbi8.updateNominee();
        rbi8.freezeAccount();
        rbi8.unfreezeAccount();

        System.out.println("-------------------------------------------------------");
        System.out.println("Union Bank schmes");
        Rbi rbi9=new UnionBank();
        rbi9.kyc();
        rbi9.openAccount();
        rbi9.closeAccount();
        rbi9.depositMoney();
        rbi9.withdrawMoney();
        rbi9.transferMoney();
        rbi9.checkBalance();
        rbi9.updateAccountDetails();
        rbi9.verifyCustomer();
        rbi9.issueDebitCard();
        rbi9.blockDebitCard();
        rbi9.activateDebitCard();
        rbi9.issueCreditCard();
        rbi9.blockCreditCard();
        rbi9.approveLoan();
        rbi9.rejectLoan();
        rbi9.calculateInterest();
        rbi9.updateInterestRate();
        rbi9.checkKycStatus();
        rbi9.updateKycDetails();
        rbi9.generateBankStatement();
        rbi9.processCheque();
        rbi9.stopChequePayment();
        rbi9.updateNominee();
        rbi9.freezeAccount();
        rbi9.unfreezeAccount();


        System.out.println("-------------------------------------------------------");
        System.out.println(" Indianbank  schmes");
        Rbi rbi10=new IndianBank();
        rbi10.kyc();
        rbi10.openAccount();
        rbi10.closeAccount();
        rbi10.depositMoney();
        rbi10.withdrawMoney();
        rbi10.transferMoney();
        rbi10.checkBalance();
        rbi10.updateAccountDetails();
        rbi10.verifyCustomer();
        rbi10.issueDebitCard();
        rbi10.blockDebitCard();
        rbi10.activateDebitCard();
        rbi10.issueCreditCard();
        rbi10.blockCreditCard();
        rbi10.approveLoan();
        rbi10.rejectLoan();
        rbi10.calculateInterest();
        rbi10.updateInterestRate();
        rbi10.checkKycStatus();
        rbi10.updateKycDetails();
        rbi10.generateBankStatement();
        rbi10.processCheque();
        rbi10.stopChequePayment();
        rbi10.updateNominee();
        rbi10.freezeAccount();
        rbi10.unfreezeAccount();


        System.out.println("-------------------------------------------------------");
        System.out.println(" Bank of india  schmes");
        Rbi rbi11=new BankofIndia();
        rbi11.kyc();
        rbi11.openAccount();
        rbi11.closeAccount();
        rbi11.depositMoney();
        rbi11.withdrawMoney();
        rbi11.transferMoney();
        rbi11.checkBalance();
        rbi11.updateAccountDetails();
        rbi11.verifyCustomer();
        rbi11.issueDebitCard();
        rbi11.blockDebitCard();
        rbi11.activateDebitCard();
        rbi11.issueCreditCard();
        rbi11.blockCreditCard();
        rbi11.approveLoan();
        rbi11.rejectLoan();
        rbi11.calculateInterest();
        rbi11.updateInterestRate();
        rbi11.checkKycStatus();
        rbi11.updateKycDetails();
        rbi11.generateBankStatement();
        rbi11.processCheque();
        rbi11.stopChequePayment();
        rbi11.updateNominee();
        rbi11.freezeAccount();
        rbi11.unfreezeAccount();

        System.out.println("-------------------------------------------------------");
        System.out.println(" Central Bank of india  schmes");
        Rbi rbi12=new CentralBankofIndia();
        rbi12.kyc();
        rbi12.openAccount();
        rbi12.closeAccount();
        rbi12.depositMoney();
        rbi12.withdrawMoney();
        rbi12.transferMoney();
        rbi12.checkBalance();
        rbi12.updateAccountDetails();
        rbi12.verifyCustomer();
        rbi12.issueDebitCard();
        rbi12.blockDebitCard();
        rbi12.activateDebitCard();
        rbi12.issueCreditCard();
        rbi12.blockCreditCard();
        rbi12.approveLoan();
        rbi12.rejectLoan();
        rbi12.calculateInterest();
        rbi12.updateInterestRate();
        rbi12.checkKycStatus();
        rbi12.updateKycDetails();
        rbi12.generateBankStatement();
        rbi12.processCheque();
        rbi12.stopChequePayment();
        rbi12.updateNominee();
        rbi12.freezeAccount();
        rbi12.unfreezeAccount();

        System.out.println("-------------------------------------------------------");
        System.out.println(" Idbi Bank   schmes");
        Rbi rbi13=new IndianBank();
        rbi13.kyc();
        rbi13.openAccount();
        rbi13.closeAccount();
        rbi13.depositMoney();
        rbi13.withdrawMoney();
        rbi13.transferMoney();
        rbi13.checkBalance();
        rbi13.updateAccountDetails();
        rbi13.verifyCustomer();
        rbi13.issueDebitCard();
        rbi13.blockDebitCard();
        rbi13.activateDebitCard();
        rbi13.issueCreditCard();
        rbi13.blockCreditCard();
        rbi13.approveLoan();
        rbi13.rejectLoan();
        rbi13.calculateInterest();
        rbi13.updateInterestRate();
        rbi13.checkKycStatus();
        rbi13.updateKycDetails();
        rbi13.generateBankStatement();
        rbi13.processCheque();
        rbi13.stopChequePayment();
        rbi13.updateNominee();
        rbi13.freezeAccount();
        rbi13.unfreezeAccount();

        System.out.println("-------------------------------------------------------");
        System.out.println(" Federal Bank   schmes");
        Rbi rbi14=new FederalBank();
        rbi14.kyc();
        rbi14.openAccount();
        rbi14.closeAccount();
        rbi14.depositMoney();
        rbi14.withdrawMoney();
        rbi14.transferMoney();
        rbi14.checkBalance();
        rbi14.updateAccountDetails();
        rbi14.verifyCustomer();
        rbi14.issueDebitCard();
        rbi14.blockDebitCard();
        rbi14.activateDebitCard();
        rbi14.issueCreditCard();
        rbi14.blockCreditCard();
        rbi14.approveLoan();
        rbi14.rejectLoan();
        rbi14.calculateInterest();
        rbi14.updateInterestRate();
        rbi14.checkKycStatus();
        rbi14.updateKycDetails();
        rbi14.generateBankStatement();
        rbi14.processCheque();
        rbi14.stopChequePayment();
        rbi14.updateNominee();
        rbi14.freezeAccount();
        rbi14.unfreezeAccount();










    }
}
